services:
  vuejs:
    container_name: vuejs
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      VITE_DEV_SERVER_URL: http://localhost:5173
      VITE_DEV_SERVER_INTERNAL_URL: http://node:5173
    ports:
      - "9001:80"
    volumes:
      - ./:/var/www/html
      - ./docker-vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mysql:8.0.44
    platform: linux/amd64
    container_name: vuejs_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: yiivue_db
      MYSQL_USER: yiivue_user
      MYSQL_PASSWORD: 12345
    command: >
      --sql-mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION" --default-time-zone=+08:00

    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  node:
    image: node:20-alpine
    container_name: vuejs_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173" # Vite's default port

volumes:
  dbdata:
